eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 8070

spring:
  application:

    name: premiumCalculation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    throw-exception-if-no-handler-found: true

